# Generated by Django 5.2.5 on 2025-08-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='user_telegram',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.telegramusermodel', verbose_name='Пользователь телеграм'),
            preserve_default=False,
        ),
    ]
