# Generated by Django 5.2.5 on 2025-08-27 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Количество монет не может быть отрицательным')], verbose_name='Монеты')),
                ('is_farm', models.BooleanField(default=False, verbose_name='Фарм-флаг')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.telegramusermodel', verbose_name='Пользователь телеграм')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
