# Generated by Django 5.2.5 on 2025-08-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_club_options_alter_player_options'),
        ('users', '0002_profiletelegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFootballerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField(auto_now_add=True, verbose_name='Дата получения')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profiles', to='teams.player', verbose_name='Футболист')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footballer_cards', to='users.profiletelegramuser', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекция',
                'unique_together': {('telegram_user', 'player')},
            },
        ),
    ]
