# Generated by Django 5.2.5 on 2025-09-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfootballercollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusermodel',
            options={'verbose_name': 'Пользователя телеграмм аккаунта', 'verbose_name_plural': 'Пользователя телеграмм аккаунта'},
        ),
    ]
