# Generated by Django 5.2.5 on 2025-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_telegramusermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletelegramuser',
            name='end_datetime_farm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiletelegramuser',
            name='start_datatime_farm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
