# Generated by Django 5.2.5 on 2025-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profiletelegramuser_end_datetime_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletelegramuser',
            name='time_farm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiletelegramuser',
            name='end_datetime_farm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания фарма'),
        ),
        migrations.AlterField(
            model_name='profiletelegramuser',
            name='start_datatime_farm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала фарма'),
        ),
    ]
