# Generated by Django 5.2.5 on 2025-09-03 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profiletelegramuser_time_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletelegramuser',
            name='time_farm',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Время фарма'),
        ),
    ]
