# Generated by Django 5.2.5 on 2025-09-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profiletelegramuser_time_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramusermodel', verbose_name='Друг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='users.telegramusermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Друзья пользоваетя',
                'verbose_name_plural': 'Друзья пользоваетя',
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
