# Generated by Django 5.2.5 on 2025-08-27 10:49

import django.db.models.deletion
import teams.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=teams.services.upload_photo_player, verbose_name='Фото'),
        ),
    ]
