# Generated by Django 5.2.5 on 2025-08-27 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_club_alter_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status_card',
            field=models.CharField(choices=[('NOR', 'Обычная'), ('RA', 'Редкая'), ('LEG', 'Легендарная')], default=django.utils.timezone.now, max_length=3, verbose_name='Статус карыты'),
            preserve_default=False,
        ),
    ]
