# Generated by Django 5.2.5 on 2025-08-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_player_status_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Футбольный клуб', 'verbose_name_plural': 'Футбольные клубы'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Футболист', 'verbose_name_plural': 'Футболисты'},
        ),
    ]
