# Generated by Django 5.2.5 on 2025-09-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('correct', models.BooleanField(default=False, verbose_name='Верный')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecasts', verbose_name='Прогноз')),
            ],
        ),
    ]
