# Generated by Django 5.2.5 on 2025-09-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='forecasts',
            options={'verbose_name': 'Прогноз', 'verbose_name_plural': 'Прогнозы'},
        ),
    ]
