# Generated by Django 5.2.5 on 2025-09-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_alter_answeroption_options_alter_forecasts_options'),
        ('users', '0007_alter_profiletelegramuser_time_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.answeroption', verbose_name='Вариант ответа')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecasts', verbose_name='Прогноз')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiletelegramuser', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Ответы Пользователей',
            },
        ),
    ]
