# Generated by Django 5.2.5 on 2025-09-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_userforecasts'),
        ('users', '0007_alter_profiletelegramuser_time_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userforecasts',
            options={'verbose_name': 'Ответ Пользователя', 'verbose_name_plural': 'Ответы Пользователей'},
        ),
        migrations.AlterUniqueTogether(
            name='userforecasts',
            unique_together={('profile_user', 'forecast')},
        ),
    ]
