# Generated by Django 5.2.5 on 2025-09-05 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_alter_userforecasts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforecasts',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
