# Generated by Django 5.2.5 on 2025-09-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_userforecasts_date_creation'),
        ('users', '0007_alter_profiletelegramuser_time_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='forecasts.forecasts', verbose_name='Прогноз'),
        ),
        migrations.AlterField(
            model_name='userforecasts',
            name='profile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forecasts', to='users.profiletelegramuser', verbose_name='Профиль пользователя'),
        ),
    ]
