# Generated by Django 5.2.5 on 2025-09-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_alter_answeroption_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforecasts',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_answer_user', to='forecasts.forecasts', verbose_name='Прогноз'),
        ),
    ]
