# Generated by Django 5.2.5 on 2025-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_alter_userforecasts_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasts',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
